### ISSUE TITLE
Program doesnt run

### ISSUE THREAD

**Issue by idkjs** [oxidizing/sihl-starter#2]
Anything we can do to update this so it runs?

```sh
> esy
...
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/conf-gmp-powm-sec@opam:1
    # esy-build-package: pwd: /Users/mando/.esy/3/b/opam__s__conf_gmp_powm_sec-opam__c__1-d66c2d3a
    # esy-build-package: running: 'cc' '-c' '-I/Users/mando/.esy/3__________________________________________________________________/i/esy_gmp-0045c90a/include' './test.c'
    ./test.c:10:2: error: implicit declaration of function '__gmp_init' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            __gmp_init();
            ^
    1 error generated.
    error: command failed: 'cc' '-c' '-I/Users/mando/.esy/3__________________________________________________________________/i/esy_gmp-0045c90a/include' './test.c' (exited with 1)
    esy-build-package: exiting with errors above...

  building @opam/conf-gmp-powm-sec@opam:1
esy: exiting due to errors above
```

**Comment by aronerben** [comment]
Hi @idkjs, this project and [the minimal starter](https://github.com/oxidizing/sihl-minimal-starter) are both outdated. They are using a very old sihl version. For a more up to date example see the [demo project](https://github.com/oxidizing/sihl-demo). That one currently uses Sihl 0.5.0, but is getting upgraded to Sihl 1.0.0 soon. For a template for Sihl 1.0.0 you can look at [the template dir inside the Sihl repo](https://github.com/oxidizing/sihl/tree/master/template).

@jerben We should probably archive this and the minimal starter, what do you think?

**Comment by idkjs** [comment]
@aronerben indeed! They work if you stick and esy.json on them and specify the deps.

**Comment by aronerben** [comment]
> @aronerben indeed! They work if you stick and esy.json on them and specify the deps.

@idkjs I'm glad you got it to work! :) 

Just to reinforce my earlier point, I strongly discourage learning/looking at Sihl from this starter, since Sihl has gone through a lot of iterations since 0.1.1 and there is no documentation for 0.1.1 either, if I remember right.

**Comment by joseferben** [comment]
> @jerben We should probably archive this and the minimal starter, what do you think?

I agree. I added a deprecation notice in the readme with alternatives.
